definitions:
  task.Task:
    properties:
      created_at:
        type: integer
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: integer
    required:
    - title
    type: object
info:
  contact: {}
  description: タスク管理用のAPI
  title: タスク管理用のAPI
  version: "0.01"
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: サーバーの死活監視用のAPI
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: サーバーの死活監視用のAPI
      tags:
      - accounts
  /tasks:
    get:
      consumes:
      - application/json
      description: 指定されたオフセットとリミットでタスクの一覧を返します
      parameters:
      - description: '結果の開始位置（デフォルト: 0）'
        in: query
        name: offset
        type: integer
      - description: '取得するタスクの最大数（デフォルト: 10）'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: タスク一覧の取得に成功した場合
          schema:
            items:
              $ref: '#/definitions/task.Task'
            type: array
        "400":
          description: 不正なリクエスト（オフセットまたはリミットが数値でない場合）
        "500":
          description: 内部サーバーエラー
      summary: タスク一覧を取得する
    post:
      consumes:
      - application/json
      description: タスクを登録する
      parameters:
      - description: 登録するタスク情報
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/task.Task'
      produces:
      - application/json
      responses:
        "201":
          description: タスクが正常に作成された場合
        "400":
          description: 不正なリクエスト（バリデーションエラーやリクエスト形式のエラー）
          schema:
            type: string
        "415":
          description: サポートされていないメディアタイプ
        "500":
          description: 内部サーバーエラー
      summary: タスクを登録する
  /tasks/{id}:
    get:
      consumes:
      - application/json
      description: 指定されたIDに対応するタスクを返します
      parameters:
      - description: タスクのID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 指定されたIDのタスクを正常に取得
          schema:
            $ref: '#/definitions/task.Task'
        "400":
          description: 不正なリクエスト（IDが数値でない場合）
        "404":
          description: 指定されたIDのタスクが存在しない場合
        "500":
          description: 内部サーバーエラー
      summary: タスクを取得する
swagger: "2.0"
